language: node_js
node_js:
  - '12'

branches:
  only:
    - master

jobs:
  include:
    - stage: deploy
      name: 'Deploy hosting'
      node_js: '12'
      install:
        - yarn global add firebase-tools
        - yarn install --frozen-lockfile
      script:
        - yarn build:shell
      after_success:
        - firebase deploy --only hosting --token "$FIREBASE_TOKEN"

    - name: 'Deploy functions'
      node_js: '8'
      before_install:
        - cd functions
      install:
        - yarn global add firebase-tools
        - yarn install --frozen-lockfile
      script:
        - yarn lint
        - yarn build
      after_success:
        - firebase deploy --only functions --token "$FIREBASE_TOKEN"
